### ISSUE TITLE
Example for using collection_item in a sample/preview

### ISSUE THREAD

**Issue by julianrubisch** [maglevhq/maglev-core#100]
Sorry for posting this here in the issue tracker, but I haven't found a link to a discussion board or similar...

I'm setting up a "news preview" in my app using `collection_item` in my app and it works like a charm 🪄 

BUT: I can't figure out how to show them in an admin preview using the `sample` block. Here's what I've got:

```yml
name: "three columns with images"

category: blog

settings:
- label: "Title"
  id: title
  type: text
  default: Headline
- label: "Overview link"
  id: overview_link
  type: link
  with_text: true
  default: { text: "Link", href: "#" }

blocks:
- name: "Item"
  type: item
  limit: 3
  settings:
  - label: "News Item"
    id: news_item
    type: collection_item
    collection_id: news_items

blocks_label: "Top 3 News Items"

sample:
  settings:
    title: Aktuelle News
    overview_link: { text: "Link", href: "#" }
  blocks:
  - type: item
    settings: ???
 ```
 
 This is probably hard to generalize, if it works at all, but one could potentially link to a test fixture or something?

**Comment by did** [comment]
👋 @julianrubisch, the documentation is incomplete indeed and I've to update it. 

In the meantime, you could use `any` as the id of the collection item. Something like this?

```yaml
sample:
  settings:
    title: Aktuelle News
    overview_link: { text: "Link", href: "#" }
  blocks:
  - type: item
    settings:
       news_item: 
           id: any
 ```
