### ISSUE TITLE
How to localize the YAML theme files?

### ISSUE THREAD

**Issue by mabras** [maglevhq/maglev-core#138]
Our main app supports English and Arabic. Is there a way to make the theme YAML files support both languages?

Maybe like

```
app/themes/default/sections/review/review_01.yml
```

became:
```
app/themes/default/sections/review/review_01.ar.yml
app/themes/default/sections/review/review_01.en.yml
```

Or to preserve compatibility. 

```
app/themes/default/sections/review/review_01.yml # whatever the default language is
app/themes/default/sections/review/review_01.en.yml
```

**Comment by did** [comment]
👋 @mabras Maglev can handle this use case. 

I don't have proper documentation for this yet but you should see how it's implemented here: https://github.com/maglevhq/maglev-core/blob/master/app/frontend/editor/components/dynamic-form/dynamic-input.vue#L108.

All you have to do is to put your new I18n translations keys (see the expected format in the file) in the i18n files of your main app.

For instance, within my dummy app (in this repo), I was able to change the label of the showcase section `title` setting:
```
en:
  hello: "Hello world"
  lang:
    en: "English"
    fr: "Français"

  maglev: 
    themes:
      simple:
        sections:
          showcase:
            settings:
              title: "Title 😎"
```

**Comment by did** [comment]
📚 Documentation updated: https://docs.maglev.dev/concepts/setting#translating-setting-labels

**Comment by mabras** [comment]
Unfortunately, your suggestion didn't work for me. I'm not sure why. I have tried many keys schema possibilities, and it didn't work. This also doesn't cover what I need in the first place. What I need is to be able to localize the theme content itself. This is mostly a placeholder text (lorem ipsum). In English, it's okay, but in Arabic layout it is ugly or at least not beautiful.

Thanks

**Comment by DavidGeismarLtd** [comment]
@did It is not clear how to localize the section name

**Comment by did** [comment]
@DavidGeismarLtd have you tried this?

```
en:
  hello: "Hello world"
  lang:
    en: "English"
    fr: "Français"

  maglev: 
    themes:
      simple:
        sections:
          showcase:
            name: "Showcase!"
            settings:
              title: "Title 😎"
```
