### ISSUE TITLE
Copying and pasting multi-line text to the text editor cuts off after the first line

### ISSUE THREAD

**Issue by ronb54** [maglevhq/maglev-core#166]
Hi there, I recently built a website for a client and noticed that copy and pasting text content to the editor cuts off the text after the first line.

Here's the setting I've configured:
```
blocks:
  - name: "Long Content"
    type: long_content
    limit: 1
    settings:
      - label: "Title"
        id: title
        type: text
        default: Hello
      - label: "Content"
        id: content
        type: text
        html: true
        line_break: true
        nb_rows: 20
        default: "Faucibus commodo massa rhoncus, volutpat. Dignissim sed eget risus enim."
```

Here's an example set of text I'm trying to copy/paste:
```
Job Description
JOB TITLE: Administrator
REPORTS TO: Board
```

The result is the text editor shows just "Job Description" (see screenshot).
<img width="402" alt="Image" src="https://github.com/user-attachments/assets/39064d5f-4aeb-4321-b658-98789ec6f8fa" />
It's been a frustrating experience for the client as they normally would have long text that they'd copy from Microsoft Word or some other notes app, only for their content to get cut off. And now they have to copy and paste line by line.

Thanks in advance! Let me know if you need more context or info. I'm also happy to get a PR going but I might need some hints on where to generally look.
