### ISSUE TITLE
Add possibility to add a defaut text for link setting 

### ISSUE THREAD

**Issue by patdec** [maglevhq/maglev-core#4]
For now, in the settings part of section yml, we can add a default href for `link` type.

```yml
 - label: "Bouton"
    id: button
    type: link
    default: '#'
```

We have to create a separate new setting if we want to insert a default text between the `a` tags. 

```yml
 - label: "Bouton Text"
    id: button_text
    type: text
    default: 'Je souhaite une assistance'
```

It would be a good idea to gather these two settings into one.
