### ISSUE TITLE
Create versions of predefined pages in other locales

### ISSUE THREAD

**Issue by did** [maglevhq/maglev-core#56]
```yaml
pages:
- title: 
    en: "Home page"
    fr: "Page d'accueil"
  path: "index"
  sections:
    en:
    - type: "jumbotron"
      settings:
        title: "Let's create the product<br/>your clients<br/>will love."
        body: "<p>NoCoffee, passionated developers,<br/>creators of web applications, mobiles apps and<br/>fancy R&D projects.</p>"
       blocks: []
    - type: "showcase"
      settings: 
        title: "Our projects"
      blocks: []  
    fr: []
```
